# Generated by Django 4.2.3 on 2023-07-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadform',
            name='image',
        ),
    ]
