# Generated by Django 4.2.3 on 2023-07-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_remove_imageuploadform_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUploadForm',
            new_name='AddArt',
        ),
    ]
