# Generated by Django 4.2.3 on 2023-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_rename_imageuploadform_addart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
